apiVersion: v2
name: turbo-k8s-starter
description: A Helm chart for Kubernetes

type: application
version: 0.2.0 # Increment version due to structural changes
appVersion: "1.16.0" # Keep this aligned or manage separately

dependencies:
  - name: go-api
    version: "0.1.0" # Match the version in the subchart's Chart.yaml
    repository: "file://../../apps/go-api/helm/go-api"
    condition: go-api.enabled
  - name: hono-api
    version: "0.1.0" # Match the version in the subchart's Chart.yaml
    repository: "file://../../apps/hono-api/helm/hono-api"
    condition: hono-api.enabled
  - name: python-api
    version: "0.1.0" # Match the version in the subchart's Chart.yaml
    repository: "file://../../apps/python-api/helm/python-api"
    condition: python-api.enabled