# Default values for turbo-k8s-starter.

imagePullSecrets: []

goApi:
  replicaCount: 1
  image:
    repository: go-api
    pullPolicy: IfNotPresent
    tag: latest
  service:
    type: ClusterIP
    port: 8080
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  resources: {}
  livenessProbe:
    httpGet:
      path: /health
      port: http
  readinessProbe:
    httpGet:
      path: /health
      port: http

honoApi:
  replicaCount: 1
  image:
    repository: hono-api
    pullPolicy: IfNotPresent
    tag: latest
  service:
    type: ClusterIP
    port: 8081
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  resources: {}
  livenessProbe:
    httpGet:
      path: /health
      port: http
  readinessProbe:
    httpGet:
      path: /health
      port: http

pythonApi:
  replicaCount: 1
  image:
    repository: python-api
    pullPolicy: IfNotPresent
    tag: latest
  service:
    type: ClusterIP
    port: 8082
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  resources: {}
  livenessProbe:
    httpGet:
      path: /health
      port: http
  readinessProbe:
    httpGet:
      path: /health
      port: http

ingress:
  enabled: false
  host: "example.com"
  annotations: {}
  tls: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}