# Default values for turbo-k8s-starter umbrella chart.

# Global image pull secrets applied to all service accounts.
imagePullSecrets: []
# Example:
# imagePullSecrets:
#   - name: docker-pull-secret

# --- Subchart Enablement ---
# Enable or disable individual services.
go-api:
  enabled: true
  # Values here override defaults in apps/go-api/helm/go-api/values.yaml
  # Example:
  # replicaCount: 2
  # resources:
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  #   requests:
  #     cpu: 250m
  #     memory: 256Mi

hono-api:
  enabled: true
  # Values here override defaults in apps/hono-api/helm/hono-api/values.yaml

python-api:
  enabled: true
  # Values here override defaults in apps/python-api/helm/python-api/values.yaml

# --- Global Settings ---

ingress:
  enabled: false
  host: "turbo-k8s-starter.local" # Example host
  annotations: {}
    # Example for nginx ingress:
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  tls: []
  # Example TLS:
  # tls:
  #   - hosts:
  #       - turbo-k8s-starter.local
  #     secretName: turbo-k8s-starter-tls

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Specifies whether to automount API credentials for the service account
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Security contexts removed from here, should be set in subcharts if needed
# podSecurityContext: {}
# securityContext: {}

# Scheduling constraints removed from here, should be set in subcharts if needed
# nodeSelector: {}
# tolerations: []
# affinity: {}