apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: turbo-k8s-starter
build:
  local:
    useBuildkit: true
  artifacts:
    # Define artifacts for Skaffold to build
    - image: go-api # Use simple names matching service/subchart names
      context: .
      docker:
        dockerfile: apps/go-api/Dockerfile
    - image: hono-api
      context: .
      docker:
        dockerfile: apps/hono-api/Dockerfile
    - image: python-api
      context: .
      docker:
        dockerfile: apps/python-api/Dockerfile
deploy:
  helm:
    releases:
      - name: turbo-k8s-starter # Name of the Helm release
        chartPath: helm/turbo-k8s-starter # Path to the umbrella chart
        # Use setValueTemplates to inject built image names into subchart values
        setValueTemplates:
          go-api.image.repository: "{{.IMAGE_REPO_go_api}}"
          go-api.image.tag: "{{.IMAGE_TAG_go_api}}"
          hono-api.image.repository: "{{.IMAGE_REPO_hono_api}}"
          hono-api.image.tag: "{{.IMAGE_TAG_hono_api}}"
          python-api.image.repository: "{{.IMAGE_REPO_python_api}}"
          python-api.image.tag: "{{.IMAGE_TAG_python_api}}"
        # Set values for the umbrella chart
        setValues:
          # Example: Enable ingress if needed for local dev
          ingress.enabled: true
          ingress.host: turbo-k8s-starter.local
          # Ensure subcharts are enabled
          go-api.enabled: true
          hono-api.enabled: true
          python-api.enabled: true
        # Optional: Specify namespace
        # namespace: default